services:
  app:
    build:
      context: .
    depends_on:
      - translator
    ports:
      - 5000:5000
  translator:
    image: mdtoolkit/mdtranslator-rails:2.20.0-beta.11
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_SERVE_STATIC_FILES: true
    ports:
      - 8080:8080
