services:
  app:
    build:
      context: .
    depends_on:
      - translator
    ports:
      - 5000:5000
  translator:
    image: mdtoolkit/mdtranslator-rails:2.20.0-beta.11
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_SERVE_STATIC_FILES: true
      RAILS_RELATIVE_URL_ROOT: /translator
    ports:
      - 9999:8080
  proxy:
    image: nginx:1.27.4
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx_certs/:/etc/ca-certificates/
    depends_on:
      - app